# NumPy Linear Algebra
Converted for Google Colab.

In [ ]:
import numpy as np

## Creating Matrices and Vectors

In [ ]:
v=np.array([1,2,3])
A=np.array([[1,2],[3,4]])
I=np.eye(3)
print(v)
print(A)
print(I)

[1 2 3]
[[1 2]
 [3 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Exercise
Write your solution below.

In [ ]:
import numpy as np

# 1. Create a 4x4 identity matrix and print it
identity_matrix = np.eye(4)
print("4x4 Identity Matrix:\n", identity_matrix)

# 2. Create a 3x3 matrix filled with 7
sevens_matrix = np.full((3, 3), 7)
print("\n3x3 Matrix filled with 7:\n", sevens_matrix)

# 3. Create 10 evenly spaced numbers between 0 and 1
linspace_array = np.linspace(0, 1, 10)
print("\n10 evenly spaced numbers between 0 and 1:\n", linspace_array)

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

3x3 Matrix filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

10 evenly spaced numbers between 0 and 1:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Matrix Multiplication

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A*B)
print(A@B)

### Exercise
Write your solution below.

In [ ]:
import numpy as np

# Define matrices
matrix_1 = np.array([[2, 0], [0, 2]])
matrix_2 = np.array([[1, 2], [3, 4]])

# Perform matrix multiplication
result = matrix_1 @ matrix_2
print(result)

[[2 4]
 [6 8]]


## Transpose

In [ ]:
A=np.array([[1,2,3],[4,5,6]])
print(A.T)

### Exercise
Write your solution below.

In [ ]:
import numpy as np

# 1. Create a 3x5 matrix
A = np.arange(15).reshape(3, 5)

# Confirm its transpose has shape (5, 3)
shape_A = A.shape
shape_A_T = A.T.shape

print(f"Matrix A:\n{A}")
print(f"Original shape of A: {shape_A}")
print(f"Shape of A transpose (A.T): {shape_A_T}\n")

# 2. Verify (A @ B).T == B.T @ A.T
# Create a matching matrix B (5x2) so matrix multiplication (A @ B) is valid
B = np.arange(10).reshape(5, 2)

# Compute both sides of the identity equation
left_side = (A @ B).T
right_side = B.T @ A.T

# Check if all elements match perfectly
identity_holds = np.allclose(left_side, right_side)

print(f"Matrix B:\n{B}")
print(f"\nLeft side: (A @ B).T =\n{left_side}")
print(f"Right side: B.T @ A.T =\n{right_side}")
print(f"\nDoes (A @ B).T equal B.T @ A.T? {identity_holds}")

Matrix A:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Original shape of A: (3, 5)
Shape of A transpose (A.T): (5, 3)

Matrix B:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Left side: (A @ B).T =
[[ 60 160 260]
 [ 70 195 320]]
Right side: B.T @ A.T =
[[ 60 160 260]
 [ 70 195 320]]

Does (A @ B).T equal B.T @ A.T? True


## Determinant

In [ ]:
A=np.array([[4,2],[7,6]])
print(np.linalg.det(A))

### Exercise
Write your solution below.

In [ ]:
import numpy as np

# 1. Define the custom 3x3 matrix
A = np.array([[2, 1, 3],
              [0, 5, -1],
              [4, 2,  1]])

# 2. Define the singular matrix (Row 3 is 2 * Row 1)
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [2, 4, 6]])

# Calculate determinants
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print(f"Determinant of Matrix A: {det_A:.1f}")
print(f"Determinant of Singular Matrix B: {det_B:.1f}")

Determinant of Matrix A: -50.0
Determinant of Singular Matrix B: 0.0


## Matrix Inverse

In [ ]:
A=np.array([[4,7],[2,6]])
print(np.linalg.inv(A))

### Exercise
Write your solution below.

In [ ]:
import numpy as np

# 1. Defined singular matrix with real values (Row 3 is 2 * Row 1)
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [2, 4, 6]])

print("--- Step 1: Inverting Singular Matrix ---")
try:
    np.linalg.inv(B)
except np.linalg.LinAlgError as e:
    print(f"Caught expected error! Type: {type(e).__name__}")
    print(f"Error Message: {e}\n")


# 2. Defined full 3x3 matrix with real values
A = np.array([[2, 1, 3],
              [0, 5, -1],
              [4, 2, 1]])

print("--- Step 2: Verifying (A_inv)_inv == A ---")
# Compute the first inverse
A_inv = np.linalg.inv(A)

# Compute the inverse of the inverse
A_back = np.linalg.inv(A_inv)

# Check if they match perfectly
identity_holds = np.allclose(A, A_back)

print(f"Original Matrix A:\n{A}")
print(f"\nInverse of Inverse (A_back):\n{A_back}")
print(f"\nDoes the double inverse give back A? {identity_holds}")

--- Step 1: Inverting Singular Matrix ---
Caught expected error! Type: LinAlgError
Error Message: Singular matrix

--- Step 2: Verifying (A_inv)_inv == A ---
Original Matrix A:
[[ 2  1  3]
 [ 0  5 -1]
 [ 4  2  1]]

Inverse of Inverse (A_back):
[[ 2.  1.  3.]
 [ 0.  5. -1.]
 [ 4.  2.  1.]]

Does the double inverse give back A? True


## Linear Systems

In [ ]:
A=np.array([[2,3],[5,4]])
b=np.array([8,13])
print(np.linalg.solve(A,b))

### Exercise
Write your solution below.

In [ ]:
import numpy as np

# Define coefficient matrix A and constants vector b
A = np.array([
    [1, 1, 1],
    [0, 2, 5],
    [2, 5, -1]
])
b = np.array([6, -4, 27])

# Method 1: Using np.linalg.solve()
x_solve = np.linalg.solve(A, b)

# Method 2: Using np.linalg.inv()
x_inv = np.linalg.inv(A) @ b

print(f"Solution using solve(): {x_solve}")
print(f"Solution using inv():   {x_inv}")

Solution using solve(): [ 5.  3. -2.]
Solution using inv():   [ 5.  3. -2.]


## Eigenvalues

In [ ]:
A=np.array([[4,-2],[1,1]])
print(np.linalg.eig(A))

### Exercise
Write your solution below.

In [ ]:
import numpy as np

A = np.array([[2, 1],
              [1, 2]])

# Extract eigenvalues (lam) and eigenvectors (v)
eigenvalues, eigenvectors = np.linalg.eig(A)

print("--- Eigenpair Verifications ---")
for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    v = eigenvectors[:, i]  # Note: Eigenvectors are stored in columns

    # Calculate both sides of the equation
    lhs = A @ v
    rhs = lam * v

    print(f"\nPair {i+1} (Eigenvalue \u03bb = {lam:.1f}):")
    print(f"  A @ v = {lhs}")
    print(f"  \u03bb * v = {rhs}")
    print(f"  Do they match? {np.allclose(lhs, rhs)}")

--- Eigenpair Verifications ---

Pair 1 (Eigenvalue λ = 3.0):
  A @ v = [2.12132034 2.12132034]
  λ * v = [2.12132034 2.12132034]
  Do they match? True

Pair 2 (Eigenvalue λ = 1.0):
  A @ v = [-0.70710678  0.70710678]
  λ * v = [-0.70710678  0.70710678]
  Do they match? True


## Norms

In [ ]:
v=np.array([3,4])
print(np.linalg.norm(v))

### Exercise
Write your solution below.

In [ ]:
import numpy as np

# 1. Define a 5-dimensional vector
v = np.array([1, 2, 3, 4, 5])

# Compute the L2 norm
l2_norm = np.linalg.norm(v)

print(f"Original vector v: {v}")
print(f"L2 Norm of v:      {l2_norm:.3f}\n")


# 2. Normalize the vector to unit length (length = 1)
v_unit = v / l2_norm

# Verify its new length
new_norm = np.linalg.norm(v_unit)

print(f"Normalized vector v_unit:\n{v_unit}")
print(f"Verification Norm:        {new_norm:.1f}")
print(f"Is length exactly 1?       {np.isclose(new_norm, 1.0)}")

Original vector v: [1 2 3 4 5]
L2 Norm of v:      7.416

Normalized vector v_unit:
[0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]
Verification Norm:        1.0
Is length exactly 1?       True


## Rank

In [ ]:
A=np.array([[1,2],[2,4]])
print(np.linalg.matrix_rank(A))

### Exercise
Write your solution below.

In [ ]:
import numpy as np

# Create two independent base rows
row1 = np.array([1, 2, 3, 4])
row2 = np.array([2, 0, 1, -1])

# Create two dependent rows (combinations of rows 1 and 2)
row3 = 2 * row1               # Directly dependent on row 1
row4 = row1 + row2            # Directly dependent on row 1 and 2

# Stack them into a 4x4 matrix
A = np.vstack([row1, row2, row3, row4])

# Verify the matrix rank
matrix_rank = np.linalg.matrix_rank(A)

print(f"Constructed Matrix A:\n{A}")
print(f"\nCalculated Rank: {matrix_rank}")

Constructed Matrix A:
[[ 1  2  3  4]
 [ 2  0  1 -1]
 [ 2  4  6  8]
 [ 3  2  4  3]]

Calculated Rank: 2


## SVD

In [ ]:
A=np.array([[1,2],[3,4],[5,6]])
print(np.linalg.svd(A))

### Exercise
Write your solution below.

In [ ]:
import numpy as np

# Create a sample 3x3 matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 1. Perform SVD
U, S_diag, Vt = np.linalg.svd(A)

# Convert the 1D array of singular values into a full 3x3 diagonal matrix
S = np.diag(S_diag)

# Reconstruct the original matrix completely: A = U @ S @ Vt
A_reconstructed = U @ S @ Vt
perfect_match = np.allclose(A, A_reconstructed)

print("--- Full Reconstruction ---")
print(f"Original A:\n{A}")
print(f"\nReconstructed A:\n{A_reconstructed}")
print(f"Does full reconstruction match A? {perfect_match}\n")


# 2. Rank-1 Approximation (Keep ONLY the largest singular value)
S_approx = np.zeros_like(S)
S_approx[0, 0] = S_diag[0]  # Fix: Correctly place the largest value at index (0,0)

A_approx = U @ S_approx @ Vt

# Measure approximation error using the Frobenius norm
error_norm = np.linalg.norm(A - A_approx)

print("--- Rank-1 Approximation ---")
print(f"Approximated A:\n{A_approx}")
print(f"\nDistance (Error) between A and Approximation: {error_norm:.4f}")

--- Full Reconstruction ---
Original A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Does full reconstruction match A? True

--- Rank-1 Approximation ---
Approximated A:
[[1.73621779 2.07174246 2.40726714]
 [4.2071528  5.02018649 5.83322018]
 [6.6780878  7.96863051 9.25917322]]

Distance (Error) between A and Approximation: 1.0684
