<a href="https://colab.research.google.com/github/kavyasree2615/Nasscom15/blob/main/smart_crop_health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np;
import pandas as pd;
df = pd.DataFrame({
    'day':[1,2,3,4,5,6],
    'soilmoisture':[72,68,62,55,48,40],
    'temperature':[27,29,31,33,35,37],
    'Humidity':[78,74,70,65,60,55],
    'SoilNitrogen':[48,46,43,39,35,30],
    'CropHealthScore':[94,90,84,76,65,52],
})
df

,day,soilmoisture,temperature,Humidity,SoilNitrogen,CropHealthScore
0,1,72,27,78,48,94
1,2,68,29,74,46,90
2,3,62,31,70,43,84
3,4,55,33,65,39,76
4,5,48,35,60,35,65
5,6,40,37,55,30,52


In [30]:
d=df.copy()
for i in d:
    print(d[i])

0    1
1    2
2    3
3    4
4    5
5    6
Name: day, dtype: int64
0    72
1    68
2    62
3    55
4    48
5    40
Name: soilmoisture, dtype: int64
0    27
1    29
2    31
3    33
4    35
5    37
Name: temperature, dtype: int64
0    78
1    74
2    70
3    65
4    60
5    55
Name: Humidity, dtype: int64
0    48
1    46
2    43
3    39
4    35
5    30
Name: SoilNitrogen, dtype: int64
0    94
1    90
2    84
3    76
4    65
5    52
Name: CropHealthScore, dtype: int64


In [47]:
d=df.copy()
d["status"]=np.where(
    d['soilmoisture']<50,'low soilmoisture alert' , 'soil moisture normal'
)
print(d[['soilmoisture','status']])

   soilmoisture                  status
0            72    soil moisture normal
1            68    soil moisture normal
2            62    soil moisture normal
3            55    soil moisture normal
4            48  low soilmoisture alert
5            40  low soilmoisture alert


In [48]:
d=df.copy()
d["status"]=np.where(
    d['temperature']>35,'high temperature alert','temperature normal'
)
print(d[['temperature','status']])

   temperature                  status
0           27      temperature normal
1           29      temperature normal
2           31      temperature normal
3           33      temperature normal
4           35      temperature normal
5           37  high temperature alert


In [49]:
d=df.copy()
def crop_status(score):
   if score>80:
         return 'healthy'
   elif score >= 50 and score <=80:
         return 'UnderStress'
   else:
         return 'critical'

d["status"]=d['CropHealthScore'].apply(crop_status)
print(d[['CropHealthScore','status']])

   CropHealthScore       status
0               94      healthy
1               90      healthy
2               84      healthy
3               76  UnderStress
4               65  UnderStress
5               52  UnderStress


In [56]:
d=df.copy()
arr=np.array(d)
print(arr)

[[ 1 72 27 78 48 94]
 [ 2 68 29 74 46 90]
 [ 3 62 31 70 43 84]
 [ 4 55 33 65 39 76]
 [ 5 48 35 60 35 65]
 [ 6 40 37 55 30 52]]


In [62]:
d=df.copy()
print(d.shape)
rows , columns = arr.shape
print('rows:',rows)
print('columns:',columns)

(6, 6)
rows: 6
columns: 6


In [64]:
avg = np.mean(arr, axis=0)
print("Average of each parameter:")
print(avg)

Average of each parameter:
[ 3.5        57.5        32.         67.         40.16666667 76.83333333]
